platform :osx, '13' # Set the minimum deployment target to macOS 13

require 'yaml'

def find_plugin_path(plugin_name)
  pub_cache = ENV['PUB_CACHE'] || File.join(Dir.home, '.pub-cache')
  pubspec_lock = YAML.load_file(File.join(Dir.pwd, '..', 'pubspec.lock'))
  plugin_version = pubspec_lock['packages'][plugin_name]['version']
  plugin_path = File.join(pub_cache, 'hosted', 'pub.dev', "#{plugin_name}-#{plugin_version}", 'macos')
  unless File.exist?(plugin_path)
    raise "Plugin path not found for #{plugin_name} at #{plugin_path}"
  end
  plugin_path
end

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'audio_session', :path => find_plugin_path('audio_session')
  pod 'desktop_multi_window', :path => find_plugin_path('desktop_multi_window')
  pod 'device_info_plus', :path => find_plugin_path('device_info_plus')
  pod 'file_selector_macos', :path => find_plugin_path('file_selector_macos')
  pod 'just_audio', :path => find_plugin_path('just_audio')
  pod 'macos_window_utils', :path => find_plugin_path('macos_window_utils')
  pod 'package_info_plus', :path => find_plugin_path('package_info_plus')
  pod 'path_provider_foundation', :path => "~/.pub-cache/hosted/pub.dev/path_provider_foundation-2.4.0/darwin"
  pod 'screen_retriever', :path => find_plugin_path('screen_retriever')
  pod 'sqflite', :path => "/Users/lucas/.pub-cache/hosted/pub.dev/sqflite-2.3.3+2/darwin"
  pod 'system_theme', :path => find_plugin_path('system_theme')
  pod 'url_launcher_macos', :path => find_plugin_path('url_launcher_macos')
  pod 'video_player_avfoundation', :path => "~/.pub-cache/hosted/pub.dev/video_player_avfoundation-2.6.1/darwin"
  pod 'wakelock_plus', :path => find_plugin_path('wakelock_plus')
  pod 'webview_flutter_wkwebview', :path => "~/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.15.0/darwin"
  pod 'window_manager', :path => find_plugin_path('window_manager')
end