name: Build Release macOS aarch64

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Init Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: arm64

      - name: Check Flutter Version
        run: flutter doctor

      - name: Pull Dependencies
        run: flutter pub get

      - name: Create Symlink
        run: |
          mkdir -p macos/Flutter/ephemeral/.symlinks/plugins/macos_window_utils
          ln -s ~/.pub-cache/hosted/pub.dev/macos_window_utils-1.5.0/macos macos/Flutter/ephemeral/.symlinks/plugins/macos_window_utils/macos      

      - name: 打包并压缩
        run: |
          flutter build macos
          tar -czvf ShufflePlay.tar.gz -C build/macos/Build/Products/Release/ShufflePlay.app .

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: ShufflePlay
          compression-level: 0
          path: ShufflePlay.tar.gz

      # - name: 发行Release
      #   uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     draft: true
      #     files: ShufflePlay.tar.gz
