name: Build Release macOS aarch64

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Init Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: arm64

      - name: Check Flutter Version
        run: flutter doctor

      - name: Pull Dependencies
        run: flutter pub get

      - name: Create Symlink
        run: |
          mkdir -p macos/Flutter/ephemeral/.symlinks/plugins
          ln -s ~/.pub-cache/hosted/pub.dev/audio_session-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/audio_session/macos
          ln -s ~/.pub-cache/hosted/pub.dev/desktop_multi_window-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/desktop_multi_window/macos
          ln -s ~/.pub-cache/hosted/pub.dev/device_info_plus-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/device_info_plus/macos
          ln -s ~/.pub-cache/hosted/pub.dev/file_selector_macos-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/file_selector_macos/macos
          ln -s ~/.pub-cache/hosted/pub.dev/just_audio-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/just_audio/macos
          ln -s ~/.pub-cache/hosted/pub.dev/macos_window_utils-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/macos_window_utils/macos
          ln -s ~/.pub-cache/hosted/pub.dev/package_info_plus-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/package_info_plus/macos
          ln -s ~/.pub-cache/hosted/pub.dev/path_provider_foundation-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/path_provider_foundation/macos
          ln -s ~/.pub-cache/hosted/pub.dev/screen_retriever-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/screen_retriever/macos
          ln -s ~/.pub-cache/hosted/pub.dev/sqflite-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/sqflite/macos
          ln -s ~/.pub-cache/hosted/pub.dev/system_theme-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/system_theme/macos
          ln -s ~/.pub-cache/hosted/pub.dev/url_launcher_macos-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/url_launcher_macos/macos
          ln -s ~/.pub-cache/hosted/pub.dev/video_player_avfoundation-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/video_player_avfoundation/macos
          ln -s ~/.pub-cache/hosted/pub.dev/wakelock_plus-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/wakelock_plus/macos
          ln -s ~/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/webview_flutter_wkwebview/macos
          ln -s ~/.pub-cache/hosted/pub.dev/window_manager-<version>/macos macos/Flutter/ephemeral/.symlinks/plugins/window_manager/macos

      - name: 打包并压缩
        run: |
          flutter build macos --release --target-platform=darwin-arm64
          tar -czvf ShufflePlay.tar.gz -C build/macos/Build/Products/Release/ShufflePlay.app .

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: ShufflePlay
          compression-level: 0
          path: ShufflePlay.tar.gz

      # - name: 发行Release
      #   uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     draft: true
      #     files: ShufflePlay.tar.gz
